Added support for command line options
gofore/planmill-timereport-cli pull request #1
Opened 2017-01-24 16:01 UTC by bzar

1. Refactored `index.js` into `bootstrap` and `main` (before and after having a planmill client)
1. Added `lib/options.js` for handling command line options with `command-line-args` and `command-line-usage`
1. Refactored `lib/planmill.js` to be instantiated with a configuration
    1. Nicer than passing opts to all functions?
1. Implemented configuration file setting using `path.resolve` with `./config.json` as default
    1. Should have better autodetection from standard locations if not explicitly set

2017-01-25 17:12 UTC, bzar commented
Also added a system for adding config file default search locations. Paths should be added for various platforms' variants

2017-01-26 11:36 UTC, leomelin requested changes
👍 Lots of linter errors, fix pls

2017-01-26 11:36 UTC, leomelin commented on index.js
> +const main = (pm) => {
unnecessary parentheses

2017-01-26 11:36 UTC, leomelin commented on lib/options.js
> +const parse = (argv) => commandLineArgs(optionDefinitions, argv)
unnecessary parentheses

2017-01-26 11:36 UTC, leomelin commented on lib/planmill.js
> +const getConfig = (configPath) => {
unnecessary parentheses

2017-01-26 11:36 UTC, leomelin commented on lib/planmill.js
> +  process.env.HOME + '/.config/planmill/config.json',
Nice 👍

2017-01-26 11:36 UTC, leomelin commented on lib/planmill.js
> +  if(configPath) {
Missing space. Also other linter errors - run `yarn run lint`

2017-01-26 11:36 UTC, leomelin commented on lib/planmill.js
> +const instance = (options) => {
unnecessary parentheses

2017-01-28 10:45 UTC, merged